//
//  RegisterWorker.swift
//  iOSInterviewPreparation
//
//  Created by apple on 27/04/17.
//  Copyright (c) 2017 apple. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class RegisterWorker
{
  // MARK: - Business Logic
  
  func doSomeWork()
  {
    // NOTE: Do the work
  }
}
