//
//  RegisterConfigurator.swift
//  iOSInterviewPreparation
//
//  Created by apple on 27/04/17.
//  Copyright (c) 2017 apple. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension RegisterViewController: RegisterPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension RegisterInteractor: RegisterViewControllerOutput
{
}

extension RegisterPresenter: RegisterInteractorOutput
{
}

class RegisterConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = RegisterConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: RegisterViewController)
  {
    let router = RegisterRouter()
    router.viewController = viewController
    
    let presenter = RegisterPresenter()
    presenter.output = viewController
    
    let interactor = RegisterInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
