//
//  RegisterPresenter.swift
//  iOSInterviewPreparation
//
//  Created by apple on 27/04/17.
//  Copyright (c) 2017 apple. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol RegisterPresenterInput
{
  func presentSomething(response: Register.Something.Response)
}

protocol RegisterPresenterOutput: class
{
  func displaySomething(viewModel: Register.Something.ViewModel)
}

class RegisterPresenter: RegisterPresenterInput
{
  weak var output: RegisterPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: Register.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = Register.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
